'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const E=require('../../evals/acceptance/engine.cjs');const {fixture,semanticFor,copy}=require('./helpers.cjs');
function result(f,s){return E.evaluate(f.run,f.scenario,f.world,s);}
function expectCode(f,code,kind='behavior',s){const r=result(f,s);assert.equal(r.pass,false);assert.ok(r.issues.some(i=>i.code===code&&i.kind===kind),JSON.stringify(r));}
for(const answer of ['85 кг.','Масса этой модели — 85 килограммов.','Предварительно подходит по цене. Пуск насоса пока не подтверждён.'])test(`does not penalize length or truthful qualification: ${answer}`,()=>{assert.equal(result(fixture({answer})).status,'PASS');});
const pairs=[
 ['current card required',()=>fixture({expect:{minCards:1},keys:['G5']}),f=>{f.run.turns[0].productCards=[];},'MISSING_CURRENT_CARDS'],
 ['budget numerical constraint',()=>fixture({expect:{constraints:{priceMax:90000}},keys:['G5']}),f=>{const p=f.world.products.find(p=>p.key==='G8D');f.run.turns[0].productCards=[{...p,specs:p.specs}];},'CARD_CONSTRAINT'],
 ['price cannot be invented',()=>fixture({keys:['G5']}),f=>{f.run.turns[0].productCards[0].price=1;},'CARD_PRICE_MISMATCH'],
 ['exact suffix preserved',()=>fixture({keys:['G5']}),f=>{f.run.turns[0].productCards[0].name='Генератор BAKAUT-TEST G5R';},'WRONG_MODIFICATION'],
 ['exact requested product',()=>fixture({expect:{exactKeys:['G5']},keys:['G5']}),f=>{const p=f.world.products.find(p=>p.key==='G5R');f.run.turns[0].productCards=[{...p}];},'UNREQUESTED_PRODUCT'],
 ['nominal rather than peak',()=>fixture({expect:{constraints:{nominalMin:5}},keys:['G5']}),f=>{f.scenario.steps[0].expect.constraints.nominalMin=5.5;},'CARD_CONSTRAINT'],
 ['correct current class',()=>fixture({expect:{constraints:{class:'plate'}},keys:['P85']}),f=>{f.scenario.steps[0].expect.constraints.class='generator';},'CARD_CONSTRAINT'],
 ['latest independent price ranking',()=>fixture({expect:{constraints:{class:'generator',nominalMin:5,priceMax:100000},cheapestFirst:true},keys:['G5','G5R']}),f=>{f.run.turns[0].productCards.reverse();},'WRONG_PRICE_RANKING'],
 ['known catalogue absence',()=>fixture({expect:{constraints:{class:'generator',priceMax:10000},noSuitable:true,maxCards:0}}),f=>{f.scenario.steps[0].expect.constraints.priceMax=90000;},'FALSE_NO_SUITABLE'],
 ['completed tool, not plan',()=>fixture({expect:{tools:[{tool:'catalog.search',outcome:'succeeded'}]}}),f=>{f.run.turns[0].metadata.intentContract={toolRequests:[{tool:'catalog.search'}]};f.run.turns[0].metadata.toolResults=[];},'TOOL_OBLIGATION'],
 ['successful tool required',()=>fixture({expect:{tools:[{tool:'catalog.search',outcome:'succeeded'}]}}),f=>{f.run.turns[0].metadata.toolResults[0].status='error';},'TOOL_OBLIGATION'],
 ['retrieval evidence independent of card',()=>fixture({expect:{evidenceFor:['P85']}}),f=>{f.run.turns[0].metadata.toolResults=[];},'MISSING_PRODUCT_EVIDENCE'],
 ['retrieval belongs to correct model',()=>fixture({expect:{evidenceFor:['P85']}}),f=>{f.run.turns[0].metadata.toolResults[0].payload.products=f.world.products.filter(p=>p.key!=='P85');},'MISSING_PRODUCT_EVIDENCE'],
 ['idempotency public payload',()=>{const f=fixture({expect:{samePayloadOnReplay:true}});f.run.turns[0].replay={first:{answer:'85 кг',turnId:'1'},second:{answer:'85 кг',turnId:'1'}};return f;},f=>{f.run.turns[0].replay.second.turnId='other';},'IDEMPOTENCY_PAYLOAD'],
 ['privacy-preserving no contact',()=>fixture({expect:{leadRequested:false,leadCount:0}}),f=>{f.run.turns[0].leadRequested=true;},'LEAD_REQUEST_POLICY'],
 ['lead exactly once',()=>{const f=fixture({expect:{leadCount:1}});f.run.turns[0].audit.leads=[{sessionId:'session-1',id:'lead-1'}];return f;},f=>{f.run.turns[0].audit.leads.push({sessionId:'session-1',id:'lead-2'});},'LEAD_COUNT'],
 ['first useful latency, not typing',()=>fixture({expect:{maxUsefulMs:1000}}),f=>{f.run.turns[0].firstUsefulMs=10001;},'LATENCY_USEFUL'],
 ['final latency',()=>fixture({expect:{maxLatencyMs:1000}}),f=>{f.run.turns[0].elapsedMs=10001;},'LATENCY_FINAL'],
 ['no duplicated cards',()=>fixture({keys:['P85']}),f=>{f.run.turns[0].productCards.push(copy(f.run.turns[0].productCards[0]));},'DUPLICATE_CARD'],
 ['no unknown product IDs',()=>fixture({keys:['P85']}),f=>{f.run.turns[0].productCards[0].id='invented';},'UNKNOWN_PRODUCT'],
 ['correct card specifications',()=>fixture({keys:['P85']}),f=>{f.run.turns[0].productCards[0].specs['Масса']='850 кг';},'CARD_SPEC_MISMATCH'],
];
for(const [name,build,mutate,code]of pairs){test(`accept valid: ${name}`,()=>assert.equal(result(build()).status,'PASS'));test(`reject defect: ${name}`,()=>{const f=build();mutate(f);expectCode(f,code);});}
for(const [constraint,key,bad]of [ ['fuel','G5','diesel'],['voltage','G5',380],['electricStart','G5',false],['autoStart','G5',true],['remoteStart','G5',true],['weightMax','P85',84],['weightMin','P85',86],['nominalMax','G5',4.9] ])test(`independent constraint ${constraint}`,()=>{const f=fixture({keys:[key],expect:{constraints:{[constraint]:bad}}});expectCode(f,'CARD_CONSTRAINT');});
test('old card cannot satisfy new card request',()=>{const f=fixture({users:['Покажите генератор','Теперь покажите плиту'],keys:['G5']});f.scenario.steps[1].expect.minCards=1;f.run.turns[1].productCards=[];expectCode(f,'MISSING_CURRENT_CARDS');});
test('old tool cannot satisfy current fresh tool obligation',()=>{const f=fixture({users:['Поиск','Повторная независимая проверка']});f.run.turns[1].metadata.toolResults=[];f.scenario.steps[1].expect.tools=[{tool:'catalog.search',outcome:'succeeded'}];expectCode(f,'TOOL_OBLIGATION');});
test('source outage can be accepted as attempted research, not success',()=>{const f=fixture({expect:{tools:[{tool:'webFactSearch',outcome:'attempted'}]}});f.run.turns[0].metadata.toolResults=[{requestId:'w',tool:'web.researchProductFacts',status:'timeout',payload:{},warnings:[]}];assert.equal(result(f).status,'PASS');f.scenario.steps[0].expect.tools[0].outcome='fact';expectCode(f,'TOOL_OBLIGATION');});
test('verified partial research survives later failed tier',()=>{const f=fixture({expect:{tools:[{tool:'webFactSearch',outcome:'fact'}]}});f.run.turns[0].metadata.toolResults=[{requestId:'w',tool:'web.researchProductFacts',status:'ok',payload:{usedDocumentRead:true,searchDisposition:'timed_out',facts:[{evidenceVerifiedExact:true,sourceUrl:'https://example.invalid/manual',evidence:'G5 70 кг',productName:'G5',attribute:'mass',value:'70 кг'}]}}];assert.equal(result(f).status,'PASS');});
test('unverified snippet cannot prove web fact',()=>{const f=fixture({expect:{tools:[{tool:'webFactSearch',outcome:'fact'}]}});f.run.turns[0].metadata.toolResults=[{requestId:'w',tool:'web.researchProductFacts',status:'ok',payload:{usedWebSearch:true,searchDisposition:'completed',facts:[{value:'70 кг'}]}}];expectCode(f,'TOOL_OBLIGATION');});
test('recovery is not inherently wrong',()=>{const f=fixture();f.run.turns[0].transportRecovered=true;assert.equal(result(f).status,'PASS');});
test('metadata self-declared gap cannot waive required tools',()=>{const f=fixture({expect:{tools:[{tool:'catalog.search'}]}});f.run.turns[0].metadata={toolResults:[],selectionReadiness:{status:'needs_more_info',missingFacts:['pump power']}};expectCode(f,'TOOL_OBLIGATION');});
test('scoped memory uses current active facts, not history',()=>{const f=fixture({expect:{ledger:[{factKey:'budget_max_rub',value:90000,unit:'RUB',productClass:'generator'}]}});f.run.turns[0].metadata.ledgerState.factsByKey={a:{factKey:'budget_max_rub',value:70000,unit:'RUB',productClass:'plate',status:'active'},b:{factKey:'budget_max_rub',value:90000,unit:'RUB',productClass:'generator',status:'active'}};assert.equal(result(f).status,'PASS');f.run.turns[0].metadata.ledgerState.factsByKey.b.status='superseded';expectCode(f,'MEMORY_REQUIREMENT');});
test('cancelled budget not reintroduced',()=>{const f=fixture({expect:{ledger:[{factKey:'budget_max_rub',productClass:'generator',absent:true}]}});assert.equal(result(f).status,'PASS');f.run.turns[0].metadata.ledgerState.factsByKey.a={factKey:'budget_max_rub',productClass:'generator',value:90000,status:'active'};expectCode(f,'MEMORY_REQUIREMENT');});
for(const [a,au,b,bu]of [[5,'кВт',5000,'Вт'],[70,'кг',70000,'г'],['5,0 кВт','','5000 Вт',''],[90000,'RUB',90000,'₽']])test(`equivalent units ${a} ${au}`,()=>assert.equal(E.equivalent(a,au,b,bu),true));
for(const [a,au,b,bu]of [[5,'кВт',5,'кг'],[5,'кВт',5.5,'кВт'],[null,'кг',0,'кг']])test(`not equivalent ${String(a)} ${au}/${bu}`,()=>assert.equal(E.equivalent(a,au,b,bu),false));
for(const [code,mutate]of [
 ['HARNESS_UNBOUND_AUDIT',f=>{f.run.turns[0].audit.turnId='old';}],
 ['HARNESS_WORLD_CHANGED',f=>{f.run.worldHash='old';}],
 ['HARNESS_COLLECTION',f=>{f.run.harnessError={code:'bad'};}],
 ['HARNESS_BUYER_MISMATCH',f=>{f.run.turns[0].user='different';}],
 ['HARNESS_LEAD_EVIDENCE',f=>{f.scenario.steps[0].expect.leadCount=1;delete f.run.turns[0].audit.leads;}],
 ['HARNESS_INVALID_SCENARIO',f=>{f.scenario.steps[0].expect.constraints={madeUp:1};}]
])test(`infrastructure errors do not become accepted behavior: ${code}`,()=>{const f=fixture();mutate(f);const r=result(f);assert.equal(r.status,'INCONCLUSIVE');assert.ok(r.issues.some(i=>i.code===code));});
test('unhelpful keyword answer fails independent semantic criterion',()=>{const f=fixture({answer:'Генератор, насос, мощность. Полезного вывода не дам.',criteria:[{id:'helpful',severity:'critical',rule:'Give useful explanation'}]});expectCode(f,'SEMANTIC_helpful','behavior',semanticFor(f,'fail'));});
test('no semantic result is NOT success',()=>{const f=fixture({criteria:[{id:'q',severity:'critical',rule:'Useful response'}]});expectCode(f,'JUDGE_MISSING_OR_STALE','harness');});
test('semantic result from previous answer is rejected',()=>{const f=fixture({criteria:[{id:'q',severity:'critical',rule:'Useful response'}]});const s=semanticFor(f);f.run.turns[0].answer='changed';expectCode(f,'JUDGE_MISSING_OR_STALE','harness',s);});
test('invented judge quotations are rejected',()=>{const f=fixture({criteria:[{id:'q',severity:'critical',rule:'Useful response'}]});const s=semanticFor(f);s.checks[0].quotes=['never said'];expectCode(f,'JUDGE_INVENTED_QUOTE','harness',s);});
test('unknown cannot be averaged into green',()=>{const f=fixture({criteria:[{id:'q',severity:'quality',rule:'Useful response'}]});expectCode(f,'JUDGE_UNKNOWN','harness',semanticFor(f,'unknown'));});
test('cached research is allowed when fresh external research is forbidden',()=>{const f=fixture({expect:{forbidFreshResearch:true}});f.run.turns[0].metadata.toolResults=[{requestId:'w',tool:'web.researchProductFacts',status:'ok',payload:{usedWebSearch:false,usedDocumentRead:false,searchDisposition:'memory_hit'}}];assert.equal(result(f).status,'PASS');f.run.turns[0].metadata.toolResults[0].payload.usedWebSearch=true;expectCode(f,'UNNECESSARY_EXTERNAL_RESEARCH');});
test('source outage produces not-proven, not a false successful capability check',()=>{const f=fixture({expect:{tools:[{tool:'webFactSearch',outcome:'fact',allowOutage:true}]}});f.run.turns[0].metadata.toolResults=[{requestId:'w',tool:'web.researchProductFacts',status:'timeout',payload:{}}];expectCode(f,'RESEARCH_ENVIRONMENT_UNAVAILABLE','harness');});
test('price revision changes only the subsequent expected snapshot',()=>{const f=fixture({users:['initial','after price update'],keys:['G5']});f.scenario.steps[1].before={action:'set-price',key:'G5',price:84000};f.run.turns[1].productCards[0].price=84000;assert.equal(result(f).status,'PASS');f.run.turns[1].productCards[0].price=85000;expectCode(f,'CARD_PRICE_MISMATCH');});
test('known memory fact must be present, not only mentioned by the assistant',()=>{const f=fixture({expect:{rememberedFacts:[{key:'G5',attribute:'Масса',value:'70 кг'}]}});f.run.turns[0].metadata.verifiedProductFacts=[{productName:f.world.products.find(p=>p.key==='G5').name,attribute:'Масса',value:'70000 г'}];assert.equal(result(f).status,'PASS');f.run.turns[0].metadata.verifiedProductFacts=[];expectCode(f,'FACT_MEMORY_MISSING');});
test('durable outbox checked independently of agent confirmation',()=>{const f=fixture({expect:{outboxCount:1}});f.run.turns[0].audit.outbox=[{id:'o',status:'pending'}];assert.equal(result(f).status,'PASS');f.run.turns[0].audit.outbox[0].status='failed';expectCode(f,'OUTBOX_STATE');});
test('duplicate scenario reports cannot hide a failed result behind a good one',()=>{const good={scenarioId:'x',mode:'real-agent',commit:'c',worldHash:'w',suiteHash:'s',finishedAt:new Date().toISOString(),result:{status:'PASS',pass:true}};const r=E.releaseVerdict({requiredIds:['x'],reports:[good,{...good,result:{status:'FAIL',pass:false}}],commit:'c',worldHash:'w',suiteHash:'s'});assert.equal(r.status,'NOT_PROVEN');});
test('nonfinite card price is not a valid catalogue price',()=>{const f=fixture({keys:['G5']});f.run.turns[0].productCards[0].price=NaN;expectCode(f,'CARD_PRICE_MISMATCH');});
test('malformed semantic checks are inconclusive, not a crashed correct rejection',()=>{const f=fixture({criteria:[{id:'q',severity:'critical',rule:'Answer'}]});const s=semanticFor(f);s.checks={};assert.equal(result(f,s).status,'INCONCLUSIVE');});
test('invalid numeric expectation is a test configuration error',()=>{const f=fixture({expect:{constraints:{priceMax:NaN}}});assert.equal(result(f).status,'INCONCLUSIVE');});
test('null product in independent fixture is a harness error',()=>{const f=fixture();f.world.products=[null];assert.equal(result(f).status,'INCONCLUSIVE');});
test('contradictory card limits are not a valid acceptance requirement',()=>{const f=fixture({expect:{minCards:3,maxCards:1}});assert.equal(result(f).status,'INCONCLUSIVE');});
