'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {parseSse,HttpClient,collectCase}=require('../../evals/acceptance/http.cjs');
const {fixture}=require('./helpers.cjs');
async function server(fn){const s=http.createServer(fn);await new Promise(r=>s.listen(0,'127.0.0.1',r));return {s,url:`http://127.0.0.1:${s.address().port}`,close:async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));}};}
function json(res,x){res.setHeader('content-type','application/json');res.end(JSON.stringify(x));}
function sse(res,events){res.setHeader('content-type','text/event-stream');res.end(events.map(e=>`event: ${e.event}\ndata: ${JSON.stringify(e.data)}\n\n`).join(''));}
test('SSE preserves multi-line data and CRLF',()=>{const e=parseSse('event: done\r\ndata: {"answer":\r\ndata: "85 кг"}\r\n\r\n');assert.equal(e[0].data.answer,'85 кг');});
test('malformed SSE not silently accepted',()=>assert.throws(()=>parseSse('event: done\ndata: {bad}\n\n'),{code:'MALFORMED_SSE'}));
test('body timeout stays active after headers and status events',async()=>{const x=await server((_q,r)=>{r.writeHead(200,{'content-type':'text/event-stream'});r.write('event: status\ndata: {"status":"typing"}\n\n');});try{const c=new HttpClient({baseUrl:x.url,timeoutMs:50});await assert.rejects(()=>c.request('/'),{code:'HTTP_DEADLINE'});}finally{await x.close();}});
test('oversized body rejected',async()=>{const x=await server((_q,r)=>r.end('x'.repeat(200)));try{const c=new HttpClient({baseUrl:x.url,maxBytes:100});await assert.rejects(()=>c.request('/'),{code:'BODY_TOO_LARGE'});}finally{await x.close();}});
test('status events are not counted as useful answer',async()=>{const x=await server((_q,r)=>{r.writeHead(200,{'content-type':'text/event-stream'});r.write('event: status\ndata: {"status":"typing"}\n\n');setTimeout(()=>r.end('event: done\ndata: {"answer":"85 кг"}\n\n'),35);});try{const c=new HttpClient({baseUrl:x.url});const r=await c.request('/');assert.equal(r.firstUsefulMs,null);assert.ok(r.elapsedMs>=25);}finally{await x.close();}});
for(const badJoin of [false,true])test(`private admin join ${badJoin?'mismatch rejected':'success without public metadata'}`,async()=>{let gotId;const f=fixture();const d={turnId:'t1',assistantMessageId:'a1',answer:'85 кг.',productCards:[],leadRequested:false};
 const x=await server(async(q,r)=>{let text='';for await(const b of q)text+=b;if(q.url.endsWith('/messages')){gotId=JSON.parse(text).clientMessageId;assert.equal(q.headers.authorization,undefined);sse(r,[{event:'turn',data:{turnId:'t1'}},{event:'done',data:d}]);}else{assert.equal(q.headers.authorization,'Bearer fake-secret');json(r,{turns:[{id:'t1',assistantMessageId:badJoin?'wrong':'a1'}],messages:[{id:'a1',role:'assistant',content:'85 кг.',metadata:{turnId:'t1',toolResults:[]}}]});}});
 try{const c=new HttpClient({baseUrl:x.url,adminToken:'fake-secret'});if(badJoin)await assert.rejects(()=>c.send({id:'s',visitorId:'v'},'вес','stable-id'),{code:'AUDIT_JOIN_MISMATCH'});else{const t=await c.send({id:'s',visitorId:'v'},'вес','stable-id');assert.equal(t.audit.turnId,'t1');assert.equal(t.metadata.turnId,'t1');assert.equal(t.publicPayload.metadata,undefined);}assert.equal(gotId,'stable-id');}finally{await x.close();}});
test('HTTP call cap prevents hidden unlimited retry',async()=>{let calls=0;const c=new HttpClient({baseUrl:'http://localhost',maxRequests:1,fetchImpl:async()=>{calls++;return new Response('{}');}});await c.json('/one');await assert.rejects(()=>c.json('/two'),{code:'HTTP_BUDGET'});assert.equal(calls,1);});
test('collector keeps failed turn and does not retry until green',async()=>{let sends=0;const c={health:async()=>({runtime:{commitSha:'c'},answerModel:'m'}),start:async()=>({id:'s'}),send:async()=>{sends++;return {ok:false,turnId:'t',answer:'',productCards:[],error:'fixture failure'};},close:async()=>{}};const f=fixture({users:['one','two']});const r=await collectCase(c,f.scenario,f.world);assert.equal(sends,1);assert.equal(r.turns.length,1);assert.equal(r.turns[0].ok,false);});
test('mixed deployment invalidates collection',async()=>{let health=0;const f=fixture();const c={health:async()=>({runtime:{commitSha:++health===1?'a':'b'},answerModel:'m'}),start:async()=>({id:'s'}),send:async()=>f.run.turns[0],close:async()=>{}};const r=await collectCase(c,f.scenario,f.world);assert.equal(r.harnessError.code,'DEPLOYMENT_CHANGED_DURING_TEST');});
test('deliberate replay uses the same client message ID',async()=>{const ids=[];const f=fixture();const c={health:async()=>({runtime:{commitSha:'a'},answerModel:'m'}),start:async()=>({id:'s'}),send:async(_s,_u,id)=>{ids.push(id);return {...f.run.turns[0],publicPayload:{turnId:'t',answer:'85 кг'}};},close:async()=>{}};const r=await collectCase(c,f.scenario,f.world,{replay:true});assert.equal(ids.length,2);assert.equal(ids[0],ids[1]);assert.deepEqual(r.turns[0].replay.first,r.turns[0].replay.second);});
