'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');const A=require('../../evals/promptfoo/assertions.cjs');const {fixture,semanticFor}=require('./helpers.cjs');
for(const name of ['assertSupportAnswerQuality','assertBusinessRules','assertAgentTaskCompletion'])for(const good of [true,false])test(`${name} preserves independent ${good?'good':'bad'} verdict`,()=>{const f=fixture({answer:'85 кг.',criteria:[{id:'mass',severity:'critical',rule:'Mass known'}]});const r=A[name](f.run,{config:{minAnswerChars:99999},independent:{...f,semantic:semanticFor(f,good?'pass':'fail')}});assert.equal(r.pass,good);assert.equal(r.status,good?'PASS':'FAIL');});
test('legacy current cards cannot be borrowed from old turns',()=>{const f=fixture({users:['gen','plate'],keys:['G5']});f.run.turns[1].productCards=[];assert.equal(A.assertRetrievalGrounding(f.run,{config:{expectCards:true}}).pass,false);});
test('legacy planned web is not executed',()=>{const f=fixture();f.run.turns[0].metadata={intentContract:{toolRequests:[{tool:'web.researchProductFacts'}]},toolResults:[]};assert.equal(A.assertToolCallCorrectness(f.run,{config:{requiredToolsAll:['webFactSearch']}}).pass,false);});
test('legacy failed web is not successful',()=>{const f=fixture();f.run.turns[0].metadata.toolResults=[{requestId:'w',tool:'web.researchProductFacts',status:'error',payload:{}}];assert.equal(A.assertToolCallCorrectness(f.run,{config:{requiredToolsAll:['webFactSearch']}}).pass,false);});
test('legacy known-good executed tool passes structural check',()=>{const f=fixture();assert.equal(A.assertToolCallCorrectness(f.run,{config:{requiredToolsAll:['searchCatalog']}}).pass,true);});
test('legacy unknown semantics not evaluated by keywords',()=>{const f=fixture({answer:'Генератор, насос, мощность. Полезного ответа нет.'});assert.equal(A.assertSupportAnswerQuality(f.run,{config:{minAnswerChars:10}}).status,'INCONCLUSIVE');});
test('legacy boolean runtime happy and failure controls',()=>{const f=fixture();assert.equal(A.assertNoRuntimeFailure(f.run).pass,true);f.run.turns[0].ok=false;assert.equal(A.assertNoRuntimeFailure(f.run).pass,false);});
