-- 019: Electric-start knowledge injection (audit 2026-08-21, docs/electric-start-audit-2026-08-21.md)
-- Web-verified: 32 catalog cards said "ручной" but manufacturers/dealers confirm electric start.
-- 1) Fix product cards (survives until next full crawl re-sync; verified facts below persist regardless).
UPDATE products SET specs = specs || '{"стартер":"ручной и электростартер","электростартер":"есть"}'::jsonb, updated_at = now()
WHERE id IN (
  '7b3559f6-9ec4-4a5b-a559-9e10dc3db378',
  '40f45abd-e69d-4156-897e-d5f80d266faf',
  'ca767def-98ad-46a0-8207-c1df123184a0',
  'ad4f586a-ca52-4476-888b-09bfc9720ee4',
  '71b7111e-f3e7-4e7b-b7a8-5377d9b82d36',
  '7184d285-bb71-49e1-a290-ffebf572b4a7',
  '6b7515b6-5cbe-4df6-87b2-456632bd698a',
  '78c7d1a1-a268-4ebc-a76e-c23526c2638a',
  '265cfb92-6b4f-4a58-b177-afa40b847f4a',
  'c1ff0b8f-48be-46c6-a432-65b7170f2410',
  'd4514d66-1f88-4edc-ba70-f4342c389643',
  '101d1ea2-463e-4a69-8e4b-5d2881e7fce7',
  '61a4b3eb-3705-4df9-b8eb-f66c936044d1',
  '949f703a-1db2-40b0-83ba-f41df9d203e4',
  'c2ad06ea-99cc-4b78-8db6-1d0981c32851',
  '01cd59fc-f676-47f4-bf0c-208159c0490f',
  '99bb0edd-e158-4c7c-a8f4-6629ccd8753c',
  '51b29c40-602a-4066-9752-4bcd57bf8793',
  'a9879795-c9d7-4bdd-a1c0-df566ca97ccb',
  'c0023a41-ad01-4d02-8638-f940ba979d6c',
  '58ee6085-ecd6-4dc2-a7c0-09347c8a9dbf',
  'edebc12b-9019-4d5c-9df7-21449e9366bb',
  'd40726cd-6737-4fdf-be2a-39ead8d6353f',
  'b8af14f5-9679-4d9f-b051-9775700451da',
  '778876b1-2cea-454f-be9c-b8acef91835a',
  'cf360118-61e4-4aa2-804d-60779085126d',
  'a7f349e0-11cb-4550-a799-51c3bfac5b98',
  '9a600492-052f-49bb-a7ef-2d79fff10e07',
  '5ff91a96-93f9-4166-802c-3339cdb3fd30',
  '36a37c73-65f9-449e-8107-fd2e3af7e8fc',
  'dd64a291-3378-4236-b6ea-f6bf2ec6551d'
);

-- 2) Verified facts: electric start PRESENT (bilingual attribute for memory matching)
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('7b3559f6-9ec4-4a5b-a559-9e10dc3db378', 'bs6250ie', 'Генератор бензиновый инверторный BISON BS6250IE (5,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://www.bisonindustry.com/generator/inverter-generator/5000-watt-industrial-inverter-generator/', 'BISON BS6250IE specifications', 'BISON официал (bisonindustry.com): BS6250IE "start type: recoil start / electric start"; дилеры (weima/powersol/triniti): «тип запуска: Ручной, Электростартер, Дистанционный»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('40f45abd-e69d-4156-897e-d5f80d266faf', 'km2000is', 'Генератор бензиновый инверторный TOR KM2000is (2,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://eurosnab.ru/katalog/stroitelnoe/generatory/benzinovye-generatory/sinhronnye-220-v/generator-benzinovyy-invertornyy-tor-km2800i-2-8-kvt-220v-12-l-s-knopkoy-zapuska', 'TOR KM2800i с кнопкой запуска', 'Дилеры EUROSNAB/deltainzhiniring: TOR KM-серия «с кнопкой запуска», «Тип запуска: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('ca767def-98ad-46a0-8207-c1df123184a0', 'km2800i', 'Генератор бензиновый инверторный TOR KM2800i (2,8 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://eurosnab.ru/katalog/stroitelnoe/generatory/benzinovye-generatory/sinhronnye-220-v/generator-benzinovyy-invertornyy-tor-km2800i-2-8-kvt-220v-12-l-s-knopkoy-zapuska', 'TOR KM2800i с кнопкой запуска', 'Дилеры EUROSNAB/deltainzhiniring: TOR KM-серия «с кнопкой запуска», «Тип запуска: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('ad4f586a-ca52-4476-888b-09bfc9720ee4', 'km2000i', 'Генератор бензиновый инверторный TOR KM2000i (2,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://eurosnab.ru/katalog/stroitelnoe/generatory/benzinovye-generatory/sinhronnye-220-v/generator-benzinovyy-invertornyy-tor-km2800i-2-8-kvt-220v-12-l-s-knopkoy-zapuska', 'TOR KM2800i с кнопкой запуска', 'Дилеры EUROSNAB/deltainzhiniring: TOR KM-серия «с кнопкой запуска», «Тип запуска: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('71b7111e-f3e7-4e7b-b7a8-5377d9b82d36', 'g7500i', 'Генератор бензиновый инверторный SUNREKA G7500i (7,0 кВт) 11025', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('7184d285-bb71-49e1-a290-ffebf572b4a7', 'g9000is', 'Генератор бензиновый инверторный SUNREKA G9000iS (8,5 кВт) 211018', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('6b7515b6-5cbe-4df6-87b2-456632bd698a', 'g8000is', 'Генератор бензиновый инверторный SUNREKA G8000iS (7,0 кВт) 11017', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('78c7d1a1-a268-4ebc-a76e-c23526c2638a', 'g2200is', 'Генератор бензиновый инверторный SUNREKA G2200iS (1,8 кВт) 211014', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('265cfb92-6b4f-4a58-b177-afa40b847f4a', 'g3500i', 'Генератор бензиновый инверторный SUNREKA G3500i (3,5 кВт) 211019', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('c1ff0b8f-48be-46c6-a432-65b7170f2410', 'g1800is', 'Генератор бензиновый инверторный SUNREKA G1800iS (1,6 кВт) 211023', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('d4514d66-1f88-4edc-ba70-f4342c389643', 'g7000is', 'Генератор бензиновый инверторный SUNREKA G7000iS (6,0 кВт) 211016', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('101d1ea2-463e-4a69-8e4b-5d2881e7fce7', 'g4000is', 'Генератор бензиновый инверторный SUNREKA G4000iS (3,5 кВт) 211015', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('61a4b3eb-3705-4df9-b8eb-f66c936044d1', 'g1400is', 'Генератор бензиновый инверторный SUNREKA G1400iS (1,2 кВт) 211013', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://sunreka-market.ru/category/invertornye-generatory/', 'SUNREKA инверторные генераторы', 'Официал sunreka-market.ru для всей iS-линейки: «генератор оснащен электростартером — запустить можно простым нажатием кнопки START» (+ручной резервный)', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('949f703a-1db2-40b0-83ba-f41df9d203e4', 'т400 вм121э', 'Генератор бензиновый АБ8-Т400-ВМ121Э (8,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('c2ad06ea-99cc-4b78-8db6-1d0981c32851', 'т400 вм121э', 'Генератор бензиновый АБ8-Т400-ВМ121Э с АВР (8,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('01cd59fc-f676-47f4-bf0c-208159c0490f', 'т400 вм121э', 'Генератор бензиновый АБ6-Т400-ВМ121Э с АВР (6,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('99bb0edd-e158-4c7c-a8f4-6629ccd8753c', 'о230 вм121э', 'Генератор бензиновый АБ8-О230-ВМ121Э с АВР (8,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('51b29c40-602a-4066-9752-4bcd57bf8793', 'о230 вм121э', 'Генератор бензиновый АБ8-О230-ВМ121Э (8,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('a9879795-c9d7-4bdd-a1c0-df566ca97ccb', 'т400 вм121э', 'Генератор бензиновый АБ6-Т400-ВМ121Э (6,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('c0023a41-ad01-4d02-8638-f940ba979d6c', 'о230 вм121э', 'Генератор бензиновый АБ6-О230-ВМ121Э (6,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('58ee6085-ecd6-4dc2-a7c0-09347c8a9dbf', 'о230 вм121э', 'Генератор бензиновый АБ6-О230-ВМ121Э с АВР (6,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('edebc12b-9019-4d5c-9df7-21449e9366bb', 'аб17 т400 вм121э', 'Генератор бензиновый АБ17-Т400-ВМ121Э с АВР (17,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('d40726cd-6737-4fdf-be2a-39ead8d6353f', 'аб17 о230 вм121э', 'Генератор бензиновый АБ17-О230-ВМ121Э с АВР (17,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('b8af14f5-9679-4d9f-b051-9775700451da', 'аб17 т400 вм121э', 'Генератор бензиновый АБ17-Т400-ВМ121Э (17,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('778876b1-2cea-454f-be9c-b8acef91835a', 'аб17 о230 вм121э', 'Генератор бензиновый АБ17-О230-ВМ121Э (17,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('cf360118-61e4-4aa2-804d-60779085126d', 'аб10 т400 вм121э', 'Генератор бензиновый АБ10-Т400-ВМ121Э (10,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('a7f349e0-11cb-4550-a799-51c3bfac5b98', 'аб10 т400 вм121э', 'Генератор бензиновый АБ10-Т400-ВМ121Э с АВР (10,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('9a600492-052f-49bb-a7ef-2d79fff10e07', 'аб10 о230 вм121э', 'Генератор бензиновый АБ10-О230-ВМ121Э с АВР (10,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('5ff91a96-93f9-4166-802c-3339cdb3fd30', 'аб10 о230 вм121э', 'Генератор бензиновый АБ10-О230-ВМ121Э (10,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://zavod-istok.ru/catalog/generatornye-ustanovki/istok_ab8_t400_vm121e/', 'ИСТОК АБ8-Т400-ВМ121Э', 'Завод Исток zavod-istok.ru: «Система запуска: Электростартер» (суффикс Э в модели ВМ121Э = электростартер); generator.market: «Исполнение: Электростартер»', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('36a37c73-65f9-449e-8107-fd2e3af7e8fc', '6000eha', 'Генератор дизельный ТСС SDG 6000EHA с АВР (6,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://tss-sklad.ru/catalog/product/dizelnyy_generator_tss_sdg_6000eha/', 'ТСС SDG 6000EHA с электростартером', 'Официал tss-russia.com: SDG 6000EHA «Тип запуска: ручной/электростартер», установленный аккумулятор 18–21 Ач', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('dd64a291-3378-4236-b6ea-f6bf2ec6551d', '6000eha', 'Генератор дизельный ТСС SDG 6000EHA (6,0 кВт)', 'electric start электростартер', 'present — есть электростартер (ключ/кнопка), у части моделей дистанционный; ручной резервный', 'web', 'https://tss-sklad.ru/catalog/product/dizelnyy_generator_tss_sdg_6000eha/', 'ТСС SDG 6000EHA с электростартером', 'Официал tss-russia.com: SDG 6000EHA «Тип запуска: ручной/электростартер», установленный аккумулятор 18–21 Ач', 'high', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();

INSERT INTO verified_product_facts (product_id, product_key, product_name, attribute, value, source_type, source_url, source_title, evidence, confidence, status)
VALUES ('7e5b803d-5179-46ae-94bb-b09ee02debd5', 'et5500is', 'Генератор бензиновый инверторный ET-POWER ET5500iS (5,0 кВт)', 'electric start электростартер', 'uncertain — источники расходятся (stabhouse: «ручной, электрический»; amper-shop: «ручной»). Требует подтверждения поставщика', 'web', 'https://stabhouse.ru/shop/39286/desc/invertornyj-generator-et-power-et5500is', 'ET-POWER ET5500iS — СтабХаус', 'Тип стартера: ручной, электрический (stabhouse.ru); Тип запуска: Ручной (amper-shop.ru). Платформа двигателя 225i-3 совпадает с BISON BS6250IE, где электро подтверждён.', 'low', 'active')
ON CONFLICT (product_key, attribute, value, source_type, coalesce(source_url, ''), status) DO UPDATE SET last_verified_at = now(), updated_at = now();
